// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC03qEWPsXbc2e6UXi8dhF5K6NLgM5OgKs',
    appId: '1:826481171173:web:3a11c25bc0097d9ce0d20c',
    messagingSenderId: '826481171173',
    projectId: 'hafilaty-caf68',
    authDomain: 'hafilaty-caf68.firebaseapp.com',
    databaseURL: 'https://hafilaty-caf68-default-rtdb.firebaseio.com',
    storageBucket: 'hafilaty-caf68.firebasestorage.app',
    measurementId: 'G-H80W1BTH6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDULR1PxZjlXxdnV4-Btx_ZF3WFf1ocsYw',
    appId: '1:826481171173:android:1e87ffc0b613be07e0d20c',
    messagingSenderId: '826481171173',
    projectId: 'hafilaty-caf68',
    databaseURL: 'https://hafilaty-caf68-default-rtdb.firebaseio.com',
    storageBucket: 'hafilaty-caf68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6sI22DVVScCSdNKi_lgTb7mxh75at_uQ',
    appId: '1:826481171173:ios:1a7f41966ee25852e0d20c',
    messagingSenderId: '826481171173',
    projectId: 'hafilaty-caf68',
    databaseURL: 'https://hafilaty-caf68-default-rtdb.firebaseio.com',
    storageBucket: 'hafilaty-caf68.firebasestorage.app',
    iosClientId: '826481171173-cv5cn7r0bet91lqqv6nl098uerpgf6c5.apps.googleusercontent.com',
    iosBundleId: 'com.example.busTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6sI22DVVScCSdNKi_lgTb7mxh75at_uQ',
    appId: '1:826481171173:ios:1a7f41966ee25852e0d20c',
    messagingSenderId: '826481171173',
    projectId: 'hafilaty-caf68',
    databaseURL: 'https://hafilaty-caf68-default-rtdb.firebaseio.com',
    storageBucket: 'hafilaty-caf68.firebasestorage.app',
    iosClientId: '826481171173-cv5cn7r0bet91lqqv6nl098uerpgf6c5.apps.googleusercontent.com',
    iosBundleId: 'com.example.busTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC03qEWPsXbc2e6UXi8dhF5K6NLgM5OgKs',
    appId: '1:826481171173:web:3b3e86865936eab9e0d20c',
    messagingSenderId: '826481171173',
    projectId: 'hafilaty-caf68',
    authDomain: 'hafilaty-caf68.firebaseapp.com',
    databaseURL: 'https://hafilaty-caf68-default-rtdb.firebaseio.com',
    storageBucket: 'hafilaty-caf68.firebasestorage.app',
    measurementId: 'G-5CJGC72JVF',
  );
}
